### ISSUE TITLE
twitter-api-v2 Web compatible

### ISSUE THREAD

**Issue by VinniciusJesus** [twitter-dart/twitter-api-v2#518]
Is this package intended to be made compatible with Flutter Web? 
Are there any difficulties with this improvement?

**Comment by myConsciousness** [comment]
Hi @VinniciusJesus !

I have designed this package to be platform independent, but there are difficulties with Flutter for Web because official Twitter does not support `CORS`.

https://twittercommunity.com/t/twitter-api-v2-public-client-no-access-control-allow-origin-header-present-cors/170402

This package would help If official supports `CORS`, but as it stands there is nothing we can do. A possible solution as of now is to separate the Flutter for Web module from the modules that use this package.

So, create a module like a batch app that runs on the back end, and use this package to communicate from that program. The results are then stored in a database or something similar, and the data is used by the Flutter for Web app.

I just envisioned this and don't know if it will actually work, but just seems to be the only way if you need it :)
