### ISSUE TITLE
Feature Request: `TwitterApi.lists.lookupTweets` is missing some arguments such as mediaFields.

### ISSUE THREAD

**Issue by ywake** [twitter-dart/twitter-api-v2#663]
# 1. Problem to solve

I want to specify mediaField, but currently it is not possible.

# 2. Proposal

Please add arguments as with other lookupTweets!

# 3. More information

**Comment by myConsciousness** [comment]
Hi @ywake ,

This is good feedback! I seem to have been looking and this argument.

I just can't confirm that it works because I already have an expired token to use the Twitter API.

Can you create a PR? Add `List<MediaField>? mediaFields` to the following abstract method.

https://github.com/twitter-dart/twitter-api-v2/blob/712cc1ded6658094043aa7795609b58b0f64f9c1/lib/src/service/lists/lists_service.dart#L420

And then add implementation like below.

https://github.com/twitter-dart/twitter-api-v2/blob/712cc1ded6658094043aa7795609b58b0f64f9c1/lib/src/service/lists/lists_service.dart#L1233

https://github.com/twitter-dart/twitter-api-v2/blob/712cc1ded6658094043aa7795609b58b0f64f9c1/lib/src/service/lists/lists_service.dart#L1249

**Comment by ywake** [comment]
Roger that! I have created a pull request. #664
